# Generated by Django 5.2.4 on 2025-07-13 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2024)),
                ('content', models.TextField(default='none')),
                ('is_published', models.BooleanField(default=True)),
                ('published_at', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
