# Generated by Django 5.2.4 on 2025-07-14 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2025, 7, 14, 10, 39, 26, 324424)),
        ),
    ]
