# Generated by Django 5.2.4 on 2025-07-14 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_images_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateField(default=datetime.datetime(2025, 7, 14, 11, 2, 12, 205259)),
        ),
    ]
