# Generated by Django 5.2.4 on 2025-07-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blooger_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogger',
            name='poster',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
