# Generated by Django 5.2.4 on 2025-07-13 21:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogger',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blogger',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
