# Generated by Django 5.2.4 on 2025-07-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_blogger_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogger',
            old_name='post',
            new_name='poster',
        ),
    ]
